sudo: false
language: python
cache:
  directories:
  - $HOME/.pip-cache/
matrix:
  include:
  - python: '3.7'
    env: DEPLOY=yes
    os: linux
  - python: '3.6'
    env: DEPLOY=no
    os: linux
  - python: '3.5'
    env: DEPLOY=no
    os: linux
  - python: '3.4'
    env: DEPLOY=no
    os: linux
  - python: '2.7'
    env: DEPLOY=no
    os: linux
install:
- pip install --cache-dir $HOME/.pip-cache --upgrade pip codecov
- pip install --cache-dir $HOME/.pip-cache --upgrade -r requirements.txt
- python setup.py develop
script:
- nosetests
after_success:
- codecov
notifications:
  email: false
deploy:
  provider: pypi
  user: philippe.pinard
  distributions: sdist bdist_wheel
  on:
    tags: true
    repo: ppinard/matplotlib-scalebar
    all_branches: true
  password:
    secure: H/8UKobwsKhiehInS9wMDTFnrMrJ/Q1sLa1BWj5yhliBc8F5BgsVbRIGktLE+5ifkpnODqH52Jj4b5BkankjjxFNHUxN+b7kl859isVmm1ywKO+eqaKJtSEOTVDfqLM17yxnp/fo+nXFiP/3Z+V/slANSDsmLvkKkxeJnV4K2OLv1DNRPmko49KGYEsoahjXAjAyBTthA5gVMw6Xl7RK19ApeQa7YhJ6nz/JC5xQwQ/d4XsyWkD3+yVDPDu2g0cKh0F6l9vmDSAw27RDEnBfM1XgLmcbEoPZqH4BY9u/IE2+gnhk/Kg8J6ZiupK+HZETzAY1wkNYVzluex+Pb8AfTsSwRlgLQ0cDy5fremopRjYULWAajySzMki8+K6QKnsKIfBA9ejlKYdyzfL3dgbyboBFW82Jh/T/tWMi2w+hyuTcEM+L7VLtTuDm/V8UZYKKJNNaJkjl3jxvDRNNvaxQF/HgvmDY6jFDXdNYRb0Jbe7ilMWmHgacQD+6fdQCtqy4EKzg77GFBlF4VF/CVMItKdq0oKnoT5xUcZEStkRIOhpuOW2WttXnqdd7GLPAis/o2zhlu8XNFjR3LOm67IwlW5uGaYh+COwKdhoSmmRCWj8BJF7RbrDEK+HQ767VdjzCM5UBYisobcrIa2/+MtvG/BoZXlADUTKWwbNMBXkhjk0=
